<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Download Studio</name>
   <tag></tag>
   <elementGuidId>7737517b-66cb-4f41-91c0-b24d847931fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-right-navbar']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.top-right-additional-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dec34356-69d2-46d5-8a39-eac286635698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top-right-additional-link</value>
      <webElementGuid>d240f0f5-3565-4eb1-900b-f0c917cab06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trackid</name>
      <type>Main</type>
      <value>open-download-popup</value>
      <webElementGuid>b70b665f-e960-4a05-bd91-ca4ee2a78dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Download Studio</value>
      <webElementGuid>6ef262c7-fa16-434e-a69d-a2247789e41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-right-navbar&quot;)/a[@class=&quot;top-right-additional-link&quot;]</value>
      <webElementGuid>62530e57-c0bb-46c5-80c2-9e4201ce762e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='top-right-navbar']/a</value>
      <webElementGuid>8a83d997-19d1-41b9-b685-02258dd14957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Download Studio')]</value>
      <webElementGuid>52b09c76-a3f3-43b8-904e-75efa88d1cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Organization_01'])[1]/following::a[1]</value>
      <webElementGuid>feca8243-09a6-49ed-a857-32742feb7362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Demo Site'])[1]/preceding::a[1]</value>
      <webElementGuid>532f706e-7d51-40a8-a3f5-470b85e5d764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KA'])[1]/preceding::a[2]</value>
      <webElementGuid>698c61e3-e037-425c-a254-7096a7abc63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Download Studio']/parent::*</value>
      <webElementGuid>b5dd715b-3ccd-4364-a819-6cd8084a3302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>c690c8ce-3101-4d45-92e1-f23a62e6ffa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Download Studio' or . = 'Download Studio')]</value>
      <webElementGuid>2a4a8236-7a49-4f23-b263-d3626aa02d72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
