<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_My Organization_01CurrentMOMy Organizat_e387fd</name>
   <tag></tag>
   <elementGuidId>5615f94c-b028-4dd1-9479-3615454de1c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='top-navbar']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#top-navbar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>584c672e-e347-4980-873e-7977a583f3d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-navbar</value>
      <webElementGuid>f4d9e536-0b29-4432-b802-7f20ab0e2e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Organization_01CurrentMOMy Organization_01AllMOMy Organization_01Create New OrganizationDownload StudioView Demo SiteKA</value>
      <webElementGuid>ff23f159-b1e7-4b1c-b591-a044ce2301bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-navbar&quot;)</value>
      <webElementGuid>9354d51e-d373-4541-aa4d-965a8a6cbfce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='top-navbar']</value>
      <webElementGuid>6c1a485e-0f25-40e7-bcc2-17875bb523d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app-content']/div</value>
      <webElementGuid>44779bfd-12e5-4fea-b033-55b74a42f0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>f946518e-cbe1-4c6b-9152-9fda704de39c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'top-navbar' and (text() = 'My Organization_01CurrentMOMy Organization_01AllMOMy Organization_01Create New OrganizationDownload StudioView Demo SiteKA' or . = 'My Organization_01CurrentMOMy Organization_01AllMOMy Organization_01Create New OrganizationDownload StudioView Demo SiteKA')]</value>
      <webElementGuid>a17a4a38-1d6c-4a1b-bcb0-3de3b82d5f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
